export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL'

export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST'
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS'
export const NEW_CATEGORY_RESET = 'NEW_CATEGORY_RESET'
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL'

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET'
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'

export const NEW_SUBCATEGORY_REQUEST = 'NEW_SUBCATEGORY_REQUEST'
export const NEW_SUBCATEGORY_SUCCESS = 'NEW_SUBCATEGORY_SUCCESS'
export const NEW_SUBCATEGORY_RESET = 'NEW_SUBCATEGORY_RESET'
export const NEW_SUBCATEGORY_FAIL = 'NEW_SUBCATEGORY_FAIL'

export const UPDATE_SUBCATEGORY_REQUEST = 'UPDATE_SUBCATEGORY_REQUEST'
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS'
export const UPDATE_SUBCATEGORY_RESET = 'UPDATE_SUBCATEGORY_RESET'
export const UPDATE_SUBCATEGORY_FAIL = 'UPDATE_SUBCATEGORY_FAIL'

export const DELETE_SUBCATEGORY_REQUEST = 'DELETE_SUBCATEGORY_REQUEST'
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS'
export const DELETE_SUBCATEGORY_RESET = 'DELETE_SUBCATEGORY_RESET'
export const DELETE_SUBCATEGORY_FAIL = 'DELETE_SUBCATEGORY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'