export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL'

export const FILTER_ORDERS_REQUEST = 'FILTER_ORDERS_REQUEST'
export const FILTER_ORDERS_SUCCESS = 'FILTER_ORDERS_SUCCESS'
export const FILTER_ORDERS_RESET = 'FILTER_ORDERS_RESET'
export const FILTER_ORDERS_FAIL = 'FILTER_ORDERS_FAIL'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDERS_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDERS_SUCCESS'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDERS_RESET'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDERS_FAIL'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDERS_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDERS_SUCCESS'
export const DELETE_ORDER_RESET = 'DELETE_ORDERS_RESET'
export const DELETE_ORDER_FAIL = 'DELETE_ORDERS_FAIL'

//admin graph week sales data
export const WEEKDATA_REQUEST = 'WEEKDATA_REQUEST'
export const WEEKDATA_SUCCESS = 'WEEKDATA_SUCCESS'
export const WEEKDATA_FAIL = 'BLOCKDATA_FAIL' 

export const CLEAR_ERRORS = 'CLEAR_ERRORS'